### PR TITLE
feat: band-aid Eternal rating class support

### LINKED ISSUE #13: Image Generator: Out Of Range Exception if Eternal difficulty scores are present in the request JSON
In short, basically title, just tried to test B30 generation and figured out it didn't work possibly because of Eternal difficulty scores being present in the request, reporting here since unable to report towards your fork of Andreal Image Generator

### Longer explanation:

Were testing some things under Windows (alongside doing some chores like updating my db) and decided to test B30 generation

Wanted to report to the repo of your fork of the image generator, but saw it has issues disabled

First it shows this error if you try to generate a preview or the image inside Arcaea Offline
```
Invalid base64-encoded string: number of data characters (25) cannot be 1 more than a multiple of 4
```

Afterwards I tried exporting request JSON to test if CLI works, but got this error instead
```
Error: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
Try `--help` for more information.
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at AndrealImageGenerator.Beans.RecordInfo..ctor(ArcSongdata recentdata) in D:\develop\283375\AndrealImageGenerator\Beans\RecordInfo.cs:line 15
   at AndrealImageGenerator.Beans.Best40Data.<>c.<get_Best30List>b__9_0(ArcSongdata i) in D:\develop\283375\AndrealImageGenerator\Beans\Best40Data.cs:line 18
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AndrealImageGenerator.Beans.Best40Data.get_Best30List() in D:\develop\283375\AndrealImageGenerator\Beans\Best40Data.cs:line 18
   at AndrealImageGenerator.Graphics.Generators.Best40Generator.Generate() in D:\develop\283375\AndrealImageGenerator\Graphics\Generators\Best40Generator.cs:line 22
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AndrealImageGenerator.Api.Api.GetUserBest30(String jsonStr, Int32 imgVersion) in D:\develop\283375\AndrealImageGenerator\Api.cs:line 83
   at Program.<Main>$(String[] args) in D:\develop\283375\AndrealImageGenerator\Program.cs:line 68
```

After which I thought it might be Eternal difficulty potentially being unsupported (since it was added just back in march), copied the database and removed all scores on Eternal charts from it, which worked and I was able to generate B30 images

### PR DESCRIPTION
**Pull request by JustVldKsh**
Adds support for Eternal difficulty that was added back in March of this year without requiring to modify arcsong.json structure in any way

Should be good enough for the time being, since the game currently doesn't have both BYD and ETR charts on any song at the same time

- Closes ArcaeaOffline/client-pyside6#13

### CODE REVIEW

**Comment by 283375** [comment]
Looks good, and you've tested this right? Like it won't complain resource missing or something?

**Comment by JustVldKsh** [comment]
Yeah, I've already compiled it and used to generate B30

At first I didn't realise I could equal `SongInfo.RatingClass` to `Difficulty` (it was treating ETR as BYD with just `Index` part of the band-aid) if ETR was in the request JSON, and started looking for other solutions before eventually coming back to that

The reason I went with that approach is because it was the simplest solution and ETR charts are basically "in the BYD slot" (index 3) in the `arcsong.json`

**Comment by JustVldKsh** [comment]
Alternative option could be to just merge the first commit and change the `arcsong.json` structure to pad out index 3 for ETR charts to be at index 4 instead

**Comment by JustVldKsh** [comment]
The summary of what I did is basically add ETR to the list of known difficulties (first commit) and make it query `arcsong.json` song difficulty index 3 instead of 4 if difficulty value is set to 4 in the request (band-aid commit)

**Comment by 283375** [comment]
I kept wanted to review this PR, but I always remember it right before I go to bed, so I've kept putting it off. Apologies for the very late response!

**Comment by JustVldKsh** [comment]
No worries, all good! Can relate to remembering about things when it's late too

**Pull request merged**
